-- MySQL Script generated by MySQL Workbench
-- Wed Jun 15 11:50:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Payments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Payments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Payments` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `Payments` ;

-- -----------------------------------------------------
-- Table `Payments`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`users_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`users_info` (
  `users_idusers` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `passport` VARCHAR(45) NOT NULL,
  `registration_date` DATE NOT NULL,
  `address` VARCHAR(60) NULL,
  `gender` VARCHAR(10) NULL,
  `phone_number` INT(9) NULL,
  `lock_date` DATE NULL,
  PRIMARY KEY (`users_idusers`),
  CONSTRAINT `fk_users_info_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `Payments`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`banks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`banks` (
  `idbanks` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `founding_date` DATE NULL,
  `bank_address` VARCHAR(45) NULL,
  PRIMARY KEY (`idbanks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`admins` (
  `idadmins` INT NOT NULL AUTO_INCREMENT,
  `banks_idbanks` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmins`),
  INDEX `fk_admins_banks1_idx` (`banks_idbanks` ASC) VISIBLE,
  CONSTRAINT `fk_admins_banks1`
    FOREIGN KEY (`banks_idbanks`)
    REFERENCES `Payments`.`banks` (`idbanks`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`credit_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`credit_cards` (
  `idcredit_cards` INT NOT NULL AUTO_INCREMENT,
  `users_idusers` INT NOT NULL,
  `banks_idbanks` INT NOT NULL,
  `card_number` BIGINT(16) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `cvc_code` INT(3) NOT NULL,
  `registration_date` DATE NOT NULL,
  `card_type` VARCHAR(45) NULL,
  PRIMARY KEY (`idcredit_cards`),
  INDEX `fk_credit_cards_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_credit_cards_banks1_idx` (`banks_idbanks` ASC) VISIBLE,
  CONSTRAINT `fk_credit_cards_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `Payments`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_credit_cards_banks1`
    FOREIGN KEY (`banks_idbanks`)
    REFERENCES `Payments`.`banks` (`idbanks`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`accounts` (
  `credit_cards_idcredit_cards` INT NOT NULL AUTO_INCREMENT,
  `balance` DOUBLE NOT NULL,
  `currency` VARCHAR(45) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `lock_date` DATE NULL,
  PRIMARY KEY (`credit_cards_idcredit_cards`),
  CONSTRAINT `fk_accounts_credit_cards1`
    FOREIGN KEY (`credit_cards_idcredit_cards`)
    REFERENCES `Payments`.`credit_cards` (`idcredit_cards`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`payments` (
  `idpayments` INT NOT NULL AUTO_INCREMENT,
  `accounts_credit_cards_idcredit_cards` INT NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `payment_date` DATE NOT NULL,
  `currency` VARCHAR(45) NOT NULL,
  `value` DOUBLE NOT NULL,
  INDEX `fk_payments_accounts1_idx` (`accounts_credit_cards_idcredit_cards` ASC) VISIBLE,
  PRIMARY KEY (`idpayments`),
  CONSTRAINT `fk_payments_accounts1`
    FOREIGN KEY (`accounts_credit_cards_idcredit_cards`)
    REFERENCES `Payments`.`accounts` (`credit_cards_idcredit_cards`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`users_has_banks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`users_has_banks` (
  `users_idusers` INT NOT NULL,
  `banks_idbanks` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `banks_idbanks`),
  INDEX `fk_users_has_banks_banks1_idx` (`banks_idbanks` ASC) VISIBLE,
  INDEX `fk_users_has_banks_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_banks_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `Payments`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_banks_banks1`
    FOREIGN KEY (`banks_idbanks`)
    REFERENCES `Payments`.`banks` (`idbanks`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`users_has_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`users_has_admins` (
  `users_idusers` INT NOT NULL,
  `admins_idadmins` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `admins_idadmins`),
  INDEX `fk_users_has_admins_admins1_idx` (`admins_idadmins` ASC) VISIBLE,
  INDEX `fk_users_has_admins_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_admins_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `Payments`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_admins_admins1`
    FOREIGN KEY (`admins_idadmins`)
    REFERENCES `Payments`.`admins` (`idadmins`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
