-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 12:41:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Payments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Payments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Payments` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci ;
USE `Payments` ;

-- -----------------------------------------------------
-- Table `Payments`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `passport` VARCHAR(10) NOT NULL,
  `phone_number` BIGINT(9) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` DOUBLE NOT NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`credit_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_number` BIGINT(16) NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  `cvccode` INT NOT NULL,
  `account_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`),
  UNIQUE INDEX `card_number_UNIQUE` (`card_number` ASC) VISIBLE,
  INDEX `fk_credit_card_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_credit_card_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_credit_card_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Payments`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_credit_card_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Payments`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `payment_date` DATETIME NOT NULL,
  `price` DOUBLE NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Payments`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`bank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `founding_date` DATETIME NOT NULL,
  `bank_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `login` VARCHAR(15) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `bank_id` INT NOT NULL,
  PRIMARY KEY (`id`, `bank_id`),
  INDEX `fk_admin_bank1_idx` (`bank_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_bank1`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Payments`.`bank` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`user_has_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`user_has_bank` (
  `user_id` INT NOT NULL,
  `bank_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `bank_id`),
  INDEX `fk_user_has_bank_bank1_idx` (`bank_id` ASC) VISIBLE,
  INDEX `fk_user_has_bank_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_bank_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Payments`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_bank_bank1`
    FOREIGN KEY (`bank_id`)
    REFERENCES `Payments`.`bank` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`.`user_has_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments`.`user_has_admin` (
  `user_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `admin_bank_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `admin_id`, `admin_bank_id`),
  INDEX `fk_user_has_admin_admin1_idx` (`admin_id` ASC, `admin_bank_id` ASC) VISIBLE,
  INDEX `fk_user_has_admin_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Payments`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_admin_admin1`
    FOREIGN KEY (`admin_id` , `admin_bank_id`)
    REFERENCES `Payments`.`admin` (`id` , `bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
